//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimDesktop.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class acompanhante
    {
        public int id_reserva { get; set; }
        public int id_quarto { get; set; }
        public string nome { get; set; }
        public string CPF { get; set; }
        public string tipo_identidade { get; set; }
        public string numero_identidade { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public string email { get; set; }
        public bool ativo { get; set; }
    
        public virtual quarto quarto { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
