//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimDesktop.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospede()
        {
            this.reserva = new HashSet<reserva>();
            this.usuario_hospede = new HashSet<usuario_hospede>();
        }
    
        public int id_hospede { get; set; }
        public string nome { get; set; }
        public string CPF { get; set; }
        public string tipo_documento { get; set; }
        public string numero_identidade { get; set; }
        public string orgao_expedidor { get; set; }
        public string funcao { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string CEP { get; set; }
        public string primeiro_endereco { get; set; }
        public string segundo_endereco { get; set; }
        public string primeiro_telefone { get; set; }
        public string segundo_telefone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_hospede> usuario_hospede { get; set; }
    }
}
