//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimDesktop.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perfil()
        {
            this.usuario_sistema = new HashSet<usuario_sistema>();
        }
    
        public int id_perfil { get; set; }
        public string nome { get; set; }
        public bool criar_reserva { get; set; }
        public bool criar_funcionario { get; set; }
        public bool criar_hospede { get; set; }
        public bool relatorios { get; set; }
        public bool admin { get; set; }
        public bool ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_sistema> usuario_sistema { get; set; }
    }
}
