//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimDesktop.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.registro_pagamento = new HashSet<registro_pagamento>();
            this.acompanhante = new HashSet<acompanhante>();
        }
    
        public int id_reserva { get; set; }
        public int id_hospede { get; set; }
        public int id_quarto { get; set; }
        public Nullable<int> id_usuarioCadastro { get; set; }
        public Nullable<int> id_usuarioCheckIn { get; set; }
        public Nullable<int> id_usuarioCheckOut { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public string ultimo_destino { get; set; }
        public string proximo_destino { get; set; }
        public string motivo_viagem { get; set; }
        public string meio_transporte { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_fim { get; set; }
        public Nullable<System.DateTime> data_checkIn { get; set; }
        public Nullable<System.DateTime> data_checkOut { get; set; }
        public Nullable<System.DateTime> data_cancelamento { get; set; }
        public bool ativo { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual hospede hospede { get; set; }
        public virtual quarto quarto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_pagamento> registro_pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acompanhante> acompanhante { get; set; }
        public virtual usuario_sistema usuario_sistema { get; set; }
        public virtual usuario_sistema usuario_sistema1 { get; set; }
        public virtual usuario_sistema usuario_sistema2 { get; set; }
    }
}
