//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimDesktop.Data.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_hospede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario_hospede()
        {
            this.usuario_cartao = new HashSet<usuario_cartao>();
        }
    
        public int id_usuarioHospede { get; set; }
        public int id_hospede { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public Nullable<System.DateTime> primeiro_acesso { get; set; }
        public Nullable<System.DateTime> ultimo_acesso { get; set; }
    
        public virtual hospede hospede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_cartao> usuario_cartao { get; set; }
    }
}
